(function(g){var window=this;'use strict';var x4=function(a){a.ma("cardstatechange",a.pk()&&a.xo()?1:0)},y4=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Kcb=function(a){var b=g.Zm(a);
a=g.bn(a);return new g.Om(b.x,b.y,a.width,a.height)},B4=function(a){a=g.Sa(a);
delete z4[a];g.fd(z4)&&A4&&A4.stop()},Mcb=function(){A4||(A4=new g.Ip(function(){Lcb()},20));
var a=A4;a.isActive()||a.start()},Lcb=function(){var a=g.Va();
g.Uc(z4,function(b){Ncb(b,a)});
g.fd(z4)||Mcb()},C4=function(a,b,c,d){g.bq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.J=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.I=0;this.C=null},Ncb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.C);a.C=b;Ocb(a,a.progress);1==a.progress?(a.j=0,B4(a),a.onFinish(),a.Gq()):a.fd()&&a.YI()},Ocb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.J[c]-a.u[c])*b+a.u[c]},Pcb=function(a,b){g.pb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.j},D4=function(a,b,c,d,e){C4.call(this,b,c,d,e);
this.element=a},Qcb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
D4.call(this,a,b,c,d,e)},Rcb=function(a){return Math.pow(a,3)},Scb=function(a){return 3*a*a-2*a*a*a},Tcb=function(a){g.E.call(this);
this.u=a||window;this.j=[]},E4=function(a){return a.baseUrl||null},F4=function(a,b){return g.Wn(g.hm(a,b),function(c){return!!c})},Ucb=function(a,b,c){function d(I){var ha=I.hovercardButton;
if(!ha)return null;ha=ha.subscribeButtonRenderer;if(!ha)return null;var X=f(ha.unsubscribedButtonText),Da=f(ha.subscribedButtonText);if(ha.subscribed){var za=f(ha.subscriberCountWithUnsubscribeText);var Za=f(ha.subscriberCountText)}else za=f(ha.subscriberCountText),Za=f(ha.subscriberCountWithSubscribeText);var db=null;if(I.signinEndpoint){db=y4(I,"signinEndpoint","webNavigationEndpointData","url");if(!db){var wa,$a;db=null==($a=g.S(null==(wa=ha.signInEndpoint)?void 0:wa.commandMetadata,g.p3))?void 0:
$a.url}if(!db)return null}return X&&(Da||db)?{subscribed:ha.subscribed,subscribeText:X,subscribeCount:za,unsubscribeText:Da,unsubscribeCount:Za,enabled:ha.enabled,signinUrl:db,classic:I.useClassicSubscribeButton}:null}
function e(I){if(I){var ha=[],X=I.videoId;X&&ha.push("v="+X);(X=I.playlistId)&&ha.push("list="+X);(I=I.startTimeSeconds)&&ha.push("t="+I);return"/watch?"+ha.join("&")}}
function f(I){if(!I)return null;var ha=I.simpleText;return ha?ha:I.runs?g.hm(I.runs,function(X){return X.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,z=null,B=!1,G=null,O=null,N=null,K=null,W=null,Z=null;if("VIDEO"===h)g.S(l,g.GM)?m=g.S(l,g.GM).url:(Z=g.S(l,g.FM),m=e(Z)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)g.S(l,g.GM)?m=g.S(l,g.GM).url:(Z=g.S(l,g.FM),m=e(Z)),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"===
h){if(B=y4(l,"browseEndpoint","browseId"))z=B,m="/channel/"+z;n=!1;q="new";(B=!!b.isSubscribe)?G=d(b):O=f(b.subscribersText)}else"WEBSITE"===h?((N=y4(l,"urlEndpoint","url"))&&(m=N),n=!0,q="new",N=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(K=f(b.productPrice)),b.additionalFeesText&&(W=f(b.additionalFeesText)),(n=y4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=y4(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:null,
oa="";if(b.metadata){var r=f(b.metadata);r&&(oa=r)}return{id:"element-"+c,type:h,title:f(b.title),metadata:oa,callToAction:f(b.callToAction),kT:b.image,iconUrl:N,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,uC:p,playlistLength:v,channelId:z,subscribeButton:G,subscribersText:O,isSubscribe:B,Ot:m||null,r4:n,sessionData:Q?{itct:Q}:null,p9:q,TA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:F4(b.impressionUrls||[],E4),f4:F4(b.hovercardShowUrls||[],E4),clickUrls:F4(l.loggingUrls||[],E4),visualElement:g.LE(b.trackingParams),productPrice:K,additionalFeesText:W,watchEndpoint:Z||null}},Vcb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:F4(a.impressionUrls||[],E4),elements:F4(a.elements||[],function(d,e){return Ucb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.LE(a.trackingParams));return c},Wcb=function(a){g.sT.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.ea=!0;this.I=0;a=a.V();this.T=g.BK(a)||"profilepage"===a.Ja;this.events=new g.aI(this);g.J(this,this.events);this.events.S(this.player,g.iE("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.jE("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Fb);this.events.S(window,"focus",this.W7);this.load();var b=g.Ze("STYLE");(g.Qe("HEAD")[0]||document.body).appendChild(b);g.jb(this,
function(){g.jf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Xcb=function(a){return a.player.getVideoData().rd?"current":a.T?"new":"current"},G4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},Ycb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Vcb(f,Xcb(a))));H4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Pw;d&&(c.postParams={ad_tracking:d});if(b=g.Dya(b))if(b=g.$d(b),b=g.Yd(b))a.B=g.My(b,c)},H4=function(a,b,c){c=void 0===c?!0:c;
a.player.lf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&Zcb(a);c=[];d=new g.gE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().u||(a.u=new g.V({G:"div",N:"ytp-ce-shadow"}),g.uS(a.player,a.u.element,4),a.C=new g.XQ(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=$cb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.uS(a.player,f.element,4);var h=new g.gE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);adb(a,f,e)}else g.ND(new g.hA("buildEndscreenElement null",
e))}a.player.Ge(c);a.Fb()}},Zcb=function(a){var b=g.NE(),c=g.OE();
c&&b&&a.endscreen.visualElement&&g.ry(g.sP)(void 0,c,b,a.endscreen.visualElement)},$cb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.TA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:I4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:J4(a,b.Ot),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.fq(b.title||"")},ra:b.title},{G:"div",N:b.uC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",ra:b.videoDuration||
void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.TA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:I4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:J4(a,b.Ot),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.fq(b.title||"")},ra:b.title},{G:"div",N:"ytp-ce-playlist-count",W:[{G:"div",N:"ytp-ce-playlist-icon"},
{G:"div",N:"ytp-ce-playlist-count-text",ra:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.TA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],X:{href:J4(a,b.Ot),target:"_blank",tabindex:"-1",dir:g.fq(b.title||"")},ra:b.title},b.subscribeButton?{G:"div",N:"ytp-ce-subscribe-container",W:[{G:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",N:"ytp-ce-channel-subscribers-text",ra:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
ra:b.metadata}:""]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:I4(b)}]};c=new g.V(c);var d=g.Re(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Qp(d,"ytp-ce-subscribe-button");if(a.player.V().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.hU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.TA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-website-title",X:{dir:g.fq(b.title||"")},ra:b.title},{G:"div",N:"ytp-ce-website-metadata",ra:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],X:{href:J4(a,b.Ot),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:I4(b)},{G:"div",N:"ytp-ce-expanding-icon",X:bdb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",N:"ytp-ce-merchandise-price-container",
W:[{G:"div",N:"ytp-ce-merchandise-price",ra:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",N:"ytp-ce-merchandise-additional-fees",ra:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.TA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-merchandise-title",X:{dir:g.fq(b.title||"")},ra:b.title},c,{G:"div",N:"ytp-ce-merchandise-metadata",ra:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:J4(a,b.Ot),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:I4(b)},{G:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",N:"ytp-ce-merchandise-invideo-cta",
ra:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Qp(c.element,"ytp-ce-placeholder");return c},I4=function(a){if(a.kT)var b=a.kT.thumbnails;
return bdb(b?b[b.length-1].url:null)},bdb=function(a){return a?{style:"background-image: url("+a+")"}:{}},adb=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.Qp(b.element,"ytp-ce-force-expand"),K4(a,c.id,!0)):(g.Sp(b.element,"ytp-ce-force-expand"),g.Sp(b.element,"ytp-ce-element-hover"),K4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){cdb(a,b,c)});
b.Ra("mouseleave",function(){ddb(a,b,c)});
a.player.V().u||b.Ra("click",function(){g.Qp(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){edb(a,c,m)});
b.Ra("keypress",function(m){edb(a,c,m)});
b.Ra("focus",function(){cdb(a,b,c)});
b.Ra("blur",function(){ddb(a,b,c)});
b.Ra("touchstart",function(){cdb(a,b,c)});
var l=g.Te("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){g.PO?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.Sp(b.element,"ytp-ce-element-hover");g.Sp(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.Te("ytp-sb-subscribe",b.element));d(g.Te("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},edb=function(a,b,c){if(b.Ot&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Pp(d,"ytp-ce-element");){g.Pp(d,"subscribe-label")&&fdb(a,b);
if(g.Pp(d,"ytp-ce-channel-subscribe"))return;d=g.kf(d)}if(!d||g.Pp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])ddb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.p9)fdb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.$d(J4(a,b.Ot)),g.ZN(g.Yd(c),void 0,b.sessionData);else{var e=g.TK(a.player.V())||a.player.getVideoData().rd,f=function(){var h=J4(a,b.Ot),l=b.sessionData,m=b.watchEndpoint,n=g.yy(h);e&&n&&(n.v||n.list)?a.player.Kn(n.v,
l,n.list,!1,void 0,m||void 0):g.XN(h,l)};
fdb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},J4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.bL(a)+b}else return"";return b},cdb=function(a,b,c){g.Pp(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Qp(b.element,"ytp-ce-element-hover"):a.player.V().u?(new g.Ip(function(){g.Qp(b.element,"ytp-ce-element-hover")},200)).start():g.Qp(b.element,"ytp-ce-element-hover"),L4(a,c.f4),K4(a,c.id,!0))},ddb=function(a,b,c){g.Sp(b.element,"ytp-ce-element-hover");
g.Sp(b.element,"ytp-ce-force-expand");K4(a,c.id,!1)},K4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Up(a.j[e].element,"ytp-ce-element-shadow-show",c)},L4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||G4(a))c&&c();else{b=gdb(a,b);var e=0,f=!1,h=new g.Ip(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.fC(b[a],d)}},fdb=function(a,b,c){L4(a,b.clickUrls,c);
(a=g.OE())&&b.r4&&g.BP(a,b.visualElement)},gdb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(hdb(b[d],c));return a},hdb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},idb=function(a){return"string"===typeof a?a:""},M4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},jdb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},N4=function(a){return a.value?a.value:null},O4=function(a){if(!a)return null;
var b=g.$d(idb(a.value));b=g.Yd(b);if(!b)return null;var c=M4(a.target,kdb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new jdb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},ldb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},odb=function(a){if(!a)return null;
var b=M4(a.type,mdb),c=M4(a.trigger,ndb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=O4(a?a:null);return b?new ldb(b,c,a):null},pdb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},qdb=function(a,b){return g.sb(a.action,b)},rdb=function(a,b){this.context=a;
this.j=b},sdb=function(a){return a.customMessage?P4("div","iv-card-message",a.customMessage):""},Q4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",N:"iv-card-image",X:{style:a},W:c}},tdb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(P4("li","",c.value));return{G:"ul",N:"iv-card-meta-info",W:b}},P4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.fq(c);return{G:a,X:b,ra:c}},udb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.bB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.bB+");");c.dir=g.fq(a.customMessage);var d=[{G:"span",ra:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",N:"iv-card-link-icon"}));return{G:"div",Ia:b,X:c,W:d}},R4=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Ni.click,5)}},vdb=function(a,b){this.merchant=a;
this.price=b},wdb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},xdb=function(a,b){return b?b:wdb(a)?"current":"new"},S4=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.tb=!1;this.Za=new Map;this.Ya=new Map;this.context.F.addEventListener(g.iE("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.jE("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)})},T4=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.ZI(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.tb=!1});
a.context.j.Ra(b,"touchmove",function(){a.tb=!0})},ydb=function(a){var b;
return(null==(b=g.S(a,g.GM))?0:b.url)?g.S(a,g.GM).url:(a=g.S(a,g.FM))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},U4=function(a,b,c){return{IU:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
gY:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
jI:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},zdb=function(a,b,c){S4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.La=this.Pb=this.B=this.isInitialized=!1;this.cards=[];this.Ib=this.T=this.Ja=this.D=this.Wa=this.j=null;this.Z=[];this.oa=this.J=this.cg=this.Fa=null;this.I=0;this.Aa=new g.Ip(function(){},c.Y.wi?4E3:3E3);
g.J(this,this.Aa);this.kb=new g.Ip(function(){});
g.J(this,this.kb);this.ya=new rdb(c,function(e,f,h,l,m,n){T4(d,e,f,h,l,m,n)});
this.ea=new g.V({G:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",N:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",N:"iv-drawer-content"}]});g.J(this,this.ea);this.C=this.ea.element;this.ib=new g.XQ(this.ea,330);g.J(this,this.ib);this.yb=g.Te("iv-drawer-header-text",this.C);this.u=g.Te("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Pb&&V4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Pb=d.B)&&W4(d)});
this.Oa=new g.aI(this);g.J(this,this.Oa);this.F.addEventListener("videodatachange",this.Is.bind(this))},Adb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){V4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){W4(a)});
var c=b.headerText;g.mf(a.yb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.LE(b.trackingParams);a.J=g.LE(b.closeTrackingParams);a.cg=g.LE(b.iconTrackingParams)},Bdb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.V().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.qE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Ni:{},zo:null,dl:e.trackingParams?g.LE(e.trackingParams):null,cg:f&&f.trackingParams?g.LE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
bB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};X4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.qE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:Y4(a,c,b,f),sponsored:!1,Ni:U4(f,e,f.command),zo:f.trackingParams?g.LE(f.trackingParams):null,dl:e.trackingParams?g.LE(e.trackingParams):null,cg:l&&l.trackingParams?g.LE(l.trackingParams):null,imageUrl:Z4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.qE(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,bB:null,title:f.title?g.qE(f.title):"",customMessage:f.callToAction?g.qE(f.callToAction):"",url:g.S(f.command,g.GM).url?O4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.GM).url}):null,onClickCommand:null};X4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.qE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Ni:U4(e,f,e.endpoint),zo:e.trackingParams?g.LE(e.trackingParams):null,dl:f.trackingParams?g.LE(f.trackingParams):null,cg:l&&l.trackingParams?g.LE(l.trackingParams):null,channelId:g.S(e.endpoint,g.o3).browseId,customMessage:e.customText?g.qE(e.customText):null,ZW:Z4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.qE(e.channelName):"",metaInfo:[e.subscriberCountText?g.qE(e.subscriberCountText):""],url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,g.o3).canonicalBaseUrl?g.S(e.endpoint,g.o3).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,g.o3).browseId}),onClickCommand:null};X4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.qE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Ni:U4(e,f,e.action),zo:e.trackingParams?g.LE(e.trackingParams):null,dl:f.trackingParams?g.LE(f.trackingParams):null,cg:l&&l.trackingParams?g.LE(l.trackingParams):null,bE:Z4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.qE(e.customMessage):null,playlistVideoCount:g.qE(e.playlistVideoCount),title:e.playlistTitle?g.qE(e.playlistTitle):"",metaInfo:[e.channelName?g.qE(e.channelName):
"",e.videoCountText?g.qE(e.videoCountText):""],url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ydb(e.action)}),onClickCommand:null};X4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.qE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Ni:U4(e,f,e.action),zo:e.trackingParams?g.LE(e.trackingParams):null,dl:f.trackingParams?g.LE(f.trackingParams):null,cg:l&&l.trackingParams?g.LE(l.trackingParams):null,bE:Z4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.qE(e.lengthString):null,customMessage:e.customMessage?g.qE(e.customMessage):null,title:e.videoTitle?g.qE(e.videoTitle):"",metaInfo:[e.channelName?g.qE(e.channelName):
"",e.viewCountText?g.qE(e.viewCountText):""],isLiveNow:!!e.badge,url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ydb(e.action)}),onClickCommand:null};X4(a,b)}}}}}a.I++},Z4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},Y4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Ddb=function(a,b){if(b=Cdb(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.qg.id),g.jf(b.DK),g.Ab(a.cards,b),a.WE(),$4(a)},V4=function(a,b,c){if(!a.B){a.ib.show();
a.Wa=new g.Ip(function(){g.Qp(a.context.F.getRootNode(),g.RW.IV_DRAWER_OPEN)},0);
a.Wa.start();a.Oa.S(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.OE();d&&a.Fa&&a.J&&g.zP(d,[a.Fa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.vV||(f.vV=!0,Edb(a.context.logger,f.qg.Ni.IU,b)),d&&g.zP(d,[f.qg.zo]);x4(a.F);c&&(a.D=new g.Ip(function(){a.Ja=a.T;a.Ib.focus()},330),a.D.start())}},W4=function(a){a.B&&(a.ib.hide(),g.Rz(a.Oa),g.Sp(a.context.F.getRootNode(),g.RW.IV_DRAWER_OPEN),a.B=!1,x4(a.F),a.D&&a.D.stop(),a.D=new g.Ip(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},Gdb=function(a){g.Rp(a.ub(),
[g.RW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.uS(a.F,a.C,5);Fdb(a);a.T=g.Te("ytp-cards-button",a.F.getRootNode());a.Ib=g.Te("iv-drawer-close-button",a.C);a.isInitialized=!0},Fdb=function(a){var b=g.Te("iv-drawer-close-button",a.C);
a.context.j.Ra(b,"click",a.u2,a);a.context.j.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.j.Ra(a.u,"scroll",a.N2,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Pp(a.F.getRootNode(),"ytp-autohide")});
a.Z.push(g.wC("iv-button-shown",a.B4,a));a.Z.push(g.wC("iv-button-hidden",a.A4,a));a.Z.push(g.wC("iv-teaser-shown",a.OZ,a));a.Z.push(g.wC("iv-teaser-hidden",a.C4,a));a.Z.push(g.wC("iv-teaser-clicked",a.NZ,a))},Hdb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.S(b.onClickCommand,g.x$a))?void 0:c.targetId)?(a.oa=b,!0):!1},Idb=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.K("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.ZL(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.S(h[0],g.wOa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
X4=function(a,b){if(!Hdb(a,b)||Idb(a,b)){var c=Jdb(a,b);
if(c){var d={qg:b,DK:c.element,vV:!1};if(!b.onClickCommand){a.isInitialized||Gdb(a);Ddb(a,b.id);var e=Kdb(a,d);g.Hb(a.cards,e,0,d);c.Ga(a.u,e);a.WE()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,$4(a),Ldb(a,d),V4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&Mdb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Mdb(a,d)}),$4(a))}}},Jdb=function(a,b){switch(b.type){case "simple":a=a.ya;
var c=b.displayDomain?{G:"div",N:"iv-card-image-text",ra:b.displayDomain}:void 0;var d=udb(b);c={G:"div",Ia:["iv-card"],W:[{G:"a",N:"iv-click-target",X:{href:b.url?N4(b.url)||"":""},W:[Q4(b.imageUrl,c),{G:"div",N:"iv-card-content",W:[P4("h2",void 0,b.title),d]}]}]};c=new g.V(c);R4(a,g.Se("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.ya;c={G:"div",Ia:["iv-card","iv-card-channel"],W:[{G:"a",Ia:["iv-click-target"],X:{href:N4(b.url)||"","data-ytid":b.channelId},W:[Q4(b.ZW),{G:"div",
N:"iv-card-content",W:[sdb(b),{G:"h2",N:"iv-card-primary-link",ra:b.title},tdb(b)]}]}]};c=new g.V(c);R4(a,g.Se("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.ya;c={G:"div",Ia:["iv-card","iv-card-playlist"],W:[{G:"a",N:"iv-click-target",X:{href:N4(b.url)||""},W:[Q4(b.bE,{G:"div",N:"iv-card-image-overlay",W:[{G:"span",N:"iv-card-playlist-video-count",ra:b.playlistVideoCount}]}),{G:"div",N:"iv-card-content",W:[sdb(b),P4("h2","iv-card-primary-link",b.title),tdb(b)]}]}]};c=new g.V(c);
R4(a,g.Se("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.ya;var e=!g.xb(b.offers);c=["iv-card"];d="";var f=udb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",N:"iv-card-offer-price",ra:f.price}),f.merchant&&e.push({G:"div",N:"iv-card-offer-merchant",ra:f.merchant}),f={G:"div",W:e});e=b.url?N4(b.url)||"":"";c={G:"div",Ia:c,X:{tabindex:"0"},W:[{G:"a",Ia:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",N:"iv-card-content",W:[b.sponsored?{G:"div",N:"iv-card-sponsored",W:["Sponsored",{G:"div",N:"iv-ad-info-container",W:[{G:"div",N:"iv-ad-info",ra:"{{adInfo}}"},{G:"div",N:"iv-ad-info-icon-container",W:[{G:"div",N:"iv-ad-info-icon"},{G:"div",N:"iv-ad-info-callout"}]}]}]}:"",{G:"a",N:"iv-click-target",X:{href:e},W:[P4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Ze("span");g.mf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Ud(d,"adInfo");R4(a,g.Se("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.ya;d=b.videoDuration?{G:"span",N:"iv-card-video-duration",ra:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],ra:"LIVE NOW"}:null;e={G:"div",Ia:["iv-card","iv-card-video"],W:[{G:"a",N:"iv-click-target",X:{href:(null==(c=b.url)?void 0:N4(c))||""},W:[Q4(b.bE,d),{G:"div",N:"iv-card-content",W:[sdb(b),P4("h2","iv-card-primary-link",b.title),tdb(b),f]}]}]};c=new g.V(e);R4(a,g.Se("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Kdb=function(a,b){if(0===a.cards.length)return 0;
a=g.tb(a.cards,function(c){return b.qg.startMs>c.qg.startMs||b.qg.startMs===c.qg.startMs&&b.qg.timestamp>=c.qg.timestamp?!0:!1});
return-1===a?0:a+1},Ndb=function(a){return a.j?"productListing"===a.j.qg.type:g.im(a.cards,function(b){return"productListing"===b.qg.type})},$4=function(a){g.Up(a.F.getRootNode(),"ytp-cards-shopping-active",Ndb(a))},Mdb=function(a,b){if(!g.Pp(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.OE(),d=a.j?a.j.qg.cg:a.cg;
c&&d&&g.AP(c,[d]);a.j=b;$4(a)}(c=a.isInitialized&&"none"==a.ub().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.qg.teaserDurationMs&&a.F.Nz(!0,{teaserText:b.qg.teaserText,durationMs:b.qg.teaserDurationMs,onClickCommand:b.qg.onClickCommand});a.kb.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&Ldb(a,b),a.kb.start(910+b.qg.teaserDurationMs))}},Ldb=function(a,b){a.ea.zb?(b=new C4([0,
a.u.scrollTop],[0,b.DK.offsetTop],600,Scb),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.xQ(a.ea,!0),a.u.scrollTop=b.DK.offsetTop,g.xQ(a.ea,!1))},a5=function(a){return a.j&&a.j.qg?a.j.qg:a.cards[0]&&a.cards[0].qg?a.cards[0].qg:null},Cdb=function(a,b){return g.sb(a.cards,function(c){return c.qg.id===b})},b5=function(a,b,c){S4.call(this,a,b);
this.annotation=c;this.isActive=!1},Odb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},c5=function(a,b,c){b5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},Pdb=function(a,b){var c=void 0===c?0:c;
var d=Kcb(b).width;g.Xm(b,d);c=new Qcb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Rcb);g.J(a,c);a.context.B.Ra(c,"begin",function(){g.cn(b,!0)});
c.play()},Sdb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],ra:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.hU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.F),a.j.Ga(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.cn(h,!1);var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.Rm(l,"right",b.image_width+"px");g.ff(a.ub(),l);a.B=new g.Ip(function(){Qdb(a,h,l)},500);
g.J(a,a.B);a.context.j.Ra(a.ub(),"mouseover",function(){Rdb(a,h,l,f,b.image_height)});
a.context.j.Ra(a.ub(),"mouseout",function(){a.B.start()})}},Rdb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.bn(b);a.j||(b.style.width=g.Wm(f.width,!0),c.style.width=g.Wm(f.width,!0));g.Rm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Rm(d,"right","1px");a.C=!0;g.cn(b,!0);a.D=new g.Ip(function(){g.Qp(this.ub(),"iv-branding-active")},0,a);
a.D.start()}},Qdb=function(a,b,c){g.Sp(a.ub(),"iv-branding-active");
a.I=new g.Ip(function(){g.cn(b,!1);a.j||(c.style.width=g.Wm(0,!0))},250);
a.I.start();a.C=!1},Tdb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},Udb=function(a,b,c){b5.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.ea=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.Ip(function(){d.j.setAttribute("aria-hidden","true");g.cn(d.B,!1);g.cn(d.u,!0)},700,this);
g.J(this,this.D)},Wdb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.ub().setAttribute("aria-hidden","true");a.ub().setAttribute("aria-label","Promotion");a.ub().tabIndex=0;var e=a.annotation.df(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",N:"iv-promo-video-duration",ra:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",N:"iv-promo-playlist-length",ra:b.playlist_length.toString()}),h.appendChild(f));e&&T4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",N:"iv-promo-txt"}),g.ne(f,N4(e)),a.j=f):a.j=a.createElement({G:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",W:[{G:"strong",ra:b.text_line_1}]});
var m=a.createElement({G:"p",W:[{G:"span",N:"iv-promo-link",ra:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],W:[{G:"span",N:"iv-button-content",ra:f}]});var p=a.createElement({G:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&T4(a,a.ub(),e,a.annotation.id,b.session_data,void 0,c)}g.Qp(a.j,"iv-click-target");
e&&T4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",ra:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",ra:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],ra:"LIVE NOW"})),g.Qp(a.j,"iv-click-target"),e&&T4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({G:"div",N:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ra(a.u,"click",function(q){Vdb(a,5E3,q)});
c.appendChild(a.u);g.cn(a.u,!1);a.context.j.Ra(a.ub(),"mouseover",a.J3,a);a.context.j.Ra(a.ub(),"mouseout",a.I3,a);a.context.j.Ra(a.ub(),"touchend",function(q){Vdb(a,5E3,q)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.E3:a.D3,a);c.appendChild(a.B);g.Rp(a.ub(),d);h&&(g.ff(a.ub(),h),n&&h.appendChild(n));g.ff(a.ub(),a.J);g.ff(a.ub(),c)},Vdb=function(a,b,c){c.stopPropagation();
Xdb(a);Ydb(a,b);a.j.focus()},Zdb=function(a){a.isCollapsed||a.T||a.C||(g.Qp(a.ub(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Xdb=function(a){a.D.stop();
a.isCollapsed&&(g.Tp(a.ub(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.cn(a.u,!1),g.cn(a.B,!0))},Ydb=function(a,b){a.C||(a.C=g.Mf(function(){$db(this);
Zdb(this)},b,a))},$db=function(a){a.C&&(g.Ja.clearTimeout(a.C),a.C=null)},aeb=function(a){this.F=a},Edb=function(a,b,c){b&&(c?d5(a,b.map(function(d){return g.xp(d,c)})):d5(a,b))},d5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.fC(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},beb=function(a){g.sT.call(this,a);
var b=this;this.ea=this.J=!1;this.loadNumber=0;this.I={};this.logger=new aeb(this.player);this.C=new g.aI(this);this.D=this.yw=null;this.events=new g.aI(this);this.gh=this.T=this.j=null;this.Z=[];g.J(this,this.C);this.C.S(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.C.S(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.C.S(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.C.S(this.player,"resize",function(d){b.ma("resize",d)});
this.C.S(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.PZ,this);this.subscribe("resize",this.aH,this);this.player.V().La.subscribe("vast_info_card_add",this.HW,this);g.J(this,this.events);this.oa=this.createElement({G:"div",N:"video-custom-annotations"});this.u=new g.V({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.uS(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ia:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({G:"div",N:"video-annotations"});
a.appendChild(this.oa);this.B.element.appendChild(a);this.jw()&&this.load();var c=this.createElement({G:"style"});(g.Qe("HEAD")[0]||document.body).appendChild(c);g.jb(this,function(){g.jf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ceb=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.cn(a,!1);return a},deb=function(a,b){b=!b.isCued()&&!g.hO(b,1024);
g.xQ(a.u,b);g.xQ(a.B,b)},eeb=function(a,b,c){a.J=!0;
a.D=g.My(b,c)},feb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(feb(a,e))}return c},jeb=function(a){var b=a.player.getVideoData();
if(b.Oa){var c=a.player.V().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Gy(h)&&h.responseXML?h.responseXML:null)&&geb(a,h)}};
g.pA()&&(d.onFinish=heb(a,d.onFinish));d.postParams={ic_only:"1"};ieb(d,c);a.J=!0;g.My(b.Oa,d)}}},ieb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.dB&&(a.postParams.ic_coll=b.dB);b.EK&&(a.postParams.ic_xml=b.EK);b.mI&&(a.postParams.ic_track=b.mI)},keb=function(a){var b=new g.V({G:"div"});
g.cn(b.element,!1);var c=new zdb(a.player,b.element,e5(a));g.J(c,b);b.Ga(a.u.element);c.QD();return c},e5=function(a){if(!a.T){var b=new Tcb(a);
g.J(a,b);var c=new g.bl(a);g.J(a,c);a.T=new Tdb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.wi)}return a.T},geb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.OE();if(e){var f=g.NE();f&&g.ry(g.rP)(void 0,e,f,[g.LE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=feb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=M4(f.type,leb),p=M4(f.style,meb),q=idb(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=odb;if(null==v)var z=null;else if(g.Na(v)){l=[];for(var B=g.w(v),G=B.next();!G.done;G=B.next()){var O=f(G.value);
O&&l.push(O)}z=l}else{var N=f(v);z=N?[N]:[]}e=m&&n?new pdb(m,n,p,z,t):null}else e=null}catch(r){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var K=ceb(f),W=null;switch(l.type){case "branding":if(f.player.V().Cd)break;f.u.element.appendChild(K);W=new c5(K,e5(f),l);break;case "promotion":g.uS(f.player,K,4),W=new Udb(K,e5(f),l)}W&&W.QD();if(f=W)g.J(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=keb(a),g.J(a,a.j));if("card"===e.type){c=a.j;var Z=e&&e.data&&e.data.card_type;
f=e.data;if(Z)switch(l=f.tracking||{},l={IU:l.impression,click:l.click,close:l.close,gY:l.teaser_impression,jI:l.teaser_click},K=f.tracking_params||{},W=null,Z){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Ni:l,zo:K.card?g.LE(K.card):null,dl:K.teaser?g.LE(K.teaser):null,cg:K.icon?g.LE(K.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,ZW:f.image_url,title:f.title,metaInfo:f.meta_info,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Ni:l,zo:K.card?g.LE(K.card):null,dl:K.teaser?
g.LE(K.teaser):null,cg:K.icon?g.LE(K.icon):null,bE:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "productListing":f.signin_url&&(W=O4({target:"current",value:f.signin_url}));Z=[];for(var Q=f.offers||[],oa=0;oa<Q.length;oa++)Z.push(new vdb(g.He(Q[oa].merchant),g.He(Q[oa].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Ni:l,zo:K.card?g.LE(K.card):null,dl:K.teaser?g.LE(K.teaser):null,cg:K.icon?g.LE(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,bB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),a9a:W,Z8a:f.signin_title?f.signin_title:void 0,Y8a:f.signin_message?f.signin_message:void 0,offers:Z,onClickCommand:null};X4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Ni:l,zo:K.card?g.LE(K.card):
null,dl:K.teaser?g.LE(K.teaser):null,cg:K.icon?g.LE(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,bB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Ni:l,zo:K.card?g.LE(K.card):null,dl:K.teaser?g.LE(K.teaser):null,cg:K.icon?g.LE(K.icon):null,bE:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},X4(c,e)}}else Adb(a.j,e);c=!0}}c&&
(x4(a.player),a.aH())},neb=function(a,b){var c=!1;
a.j||(a.j=keb(a),g.J(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Bdb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.bN(f)||(c=a.j,d=b.headerText?g.qE(b.headerText):"",g.mf(c.yb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.LE(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.LE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.cg=b.icon.infoCardIconRenderer.trackingParams?g.LE(b.icon.infoCardIconRenderer.trackingParams):null,a.aH());x4(a.player)}},oeb=function(a,b,c,d,e){if(!a.player.V().Cd){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,g.o3)&&g.S(b.navigationEndpoint,g.o3).browseId&&f.push(new ldb("openUrl","click",new jdb("/channel/"+g.S(b.navigationEndpoint,g.o3).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.VM)){d.channel_id=g.S(b.subscribeButton,g.VM).channelId;var l;b=g.S(b.subscribeButton,g.VM);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.qE(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.qE(b.subscriberCountText))):(b.subscriberCountText&&(e=g.qE(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.qE(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.S(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.p3))?void 0:m.url)||"";l={subscribeText:g.qE(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.qE(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new pdb(c,"branding","branding",f,d);l=ceb(a);a.u.element.appendChild(l);f=new c5(l,e5(a),f);f.QD();g.J(f,f);a.I[c]=f}},heb=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.isDisposed()||a.Z.push(g.Ap.zi(function(){b.apply(null,g.la(c))}))}},peb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.nS.prototype.Nz=g.ba(18,function(a,b){var c=g.JT(this.wb());c&&c.Nz(a,b)});
var z4={},A4=null;g.Ya(C4,g.bq);g.k=C4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.fd())return!1;B4(this);this.startTime=a=g.Va();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.UG();this.El("play");-1==this.j&&this.El("resume");this.j=1;var b=g.Sa(this);b in z4||(z4[b]=this);Mcb();Ncb(this,a);return!0};
g.k.stop=function(a){B4(this);this.j=0;a&&(this.progress=1);Ocb(this,this.progress);this.El("stop");this.Gq()};
g.k.pause=function(){this.fd()&&(B4(this),this.j=-1,this.El("pause"))};
g.k.qa=function(){0==this.j||this.stop(!1);this.El("destroy");C4.Gf.qa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.YI=function(){this.El("animate")};
g.k.El=function(a){this.dispatchEvent(new Pcb(a,this))};
g.Ya(Pcb,g.pb);g.Ya(D4,C4);D4.prototype.B=function(){};
D4.prototype.YI=function(){this.B();D4.Gf.YI.call(this)};
D4.prototype.Gq=function(){this.B();D4.Gf.Gq.call(this)};
D4.prototype.UG=function(){this.B();D4.Gf.UG.call(this)};
g.Ya(Qcb,D4);Qcb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Tcb,g.E);g.k=Tcb.prototype;g.k.Ra=function(a,b,c,d){c=(0,g.Ta)(c,d||this.u);a=g.Kz(a,b,c);this.j.push(a);return a};
g.k.xG=function(a,b,c,d){c=(0,g.Ta)(c,d||this.u);a=g.mna(a,b,c);this.j.push(a);return a};
g.k.Hc=function(a){g.Lz(a);g.Ab(this.j,a)};
g.k.Ff=function(){g.Lz(this.j);this.j.length=0};
g.k.qa=function(){this.Ff();g.E.prototype.qa.call(this)};g.x(Wcb,g.sT);g.k=Wcb.prototype;g.k.load=function(){g.sT.prototype.load.call(this);if(!G4(this)){var a=g.Eya(this.player.getVideoData());a?(a=Vcb(a,Xcb(this)),H4(this,a,!1)):Ycb(this)}};
g.k.unload=function(){H4(this,null);this.B&&(this.B.abort(),this.B=null);g.sT.prototype.unload.call(this)};
g.k.rh=function(a,b){return G4(this)?"loadCustomEndscreenRenderer"===a?(a=Vcb(b,"new"),H4(this,a),!0):null:null};
g.k.getOptions=function(){return G4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Fb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<qeb.length;f++){var h=Math.abs(b.width-qeb[f]);if(-1===e||d>=h)e=f,d=h}d=reb[e];this.u&&g.Rm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.an(e.element,m,f);g.Xm(e.element,n,p);g.Tp(e.element,seb);256<m||256<f?g.Qp(e.element,"ytp-ce-large-round"):96<m||96<f?g.Qp(e.element,"ytp-ce-medium-round"):g.Qp(e.element,"ytp-ce-small-round");g.Tp(e.element,teb);m=h.left+h.width/2;h=h.top+l/2;g.Qp(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Tp(e.element,reb);g.Qp(e.element,d);(e=g.Re(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Rm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())L4(this,this.endscreen.impressionUrls),(a=g.OE())&&this.endscreen.visualElement&&g.yP(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.Qp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Qp(b,"ytp-ce-shown");L4(this,c.impressionUrls);(b=g.OE())&&g.yP(b,c.visualElement);this.player.V().I&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Sp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Sp(b,"ytp-ce-shown");this.player.V().I&&this.player.Na("endscreenelementhidden",a)}};
g.k.W7=function(a){var b=this;a.target===window&&(new g.Ip(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Tp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var qeb=[346,426,470,506,570,640,853,1280,1920],reb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),teb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],seb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var kdb={Pma:"current",rKa:"new"};var mdb={CLOSE:"close",PNa:"openUrl",SUBSCRIBE:"subscribe"},ndb={ula:"click",CLOSE:"close",Ewa:"hidden",xSa:"rollOut",ySa:"rollOver",XTa:"shown"};pdb.prototype.df=function(){var a=qdb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var meb={Yga:"anchored",lZ:"branding",CHANNEL:"channel",Fma:"cta",Hwa:"highlightText",CAa:"label",PLAYLIST:"playlist",gQa:"popup",CWa:"speech",SUBSCRIBE:"subscribe",JZa:"title",VIDEO:"video",A4a:"website"},leb={lZ:"branding",sja:"card",Ooa:"drawer",Gwa:"highlight",uGa:"marker",sRa:"promotion",TEXT:"text",b6a:"widget"};g.x(S4,g.E);g.k=S4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.gE(a,b,{id:c,namespace:"annotations_module"});d&&this.Za.set(a,d);e&&this.Ya.set(a,e);this.context.F.Ge([a])};
g.k.QD=function(){this.context.u.subscribe("resize",this.WE,this)};
g.k.ub=function(){return this.element};
g.k.ZI=function(a,b,c,d,e,f){if(this.tb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.jf(this.ub())};
g.k.WE=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=N4(a);if(f){var h=xdb(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.rd||!1,n=g.yy(f||"");m&&n&&(n.v||n.list)?e.context.F.Kn(n.v,b,n.list,!1):g.ZN(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);d5(this.context.logger,c,l,d);wdb(f)||(c=g.OE(),d=b.itct,c&&d&&g.BP(c,g.LE(d)))}};
g.k.qa=function(){this.Za.clear();this.Ya.clear();g.E.prototype.qa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.x(zdb,S4);g.k=zdb.prototype;g.k.Is=function(){this.oa&&X4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.bn(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.WE=function(){var a=this.isAvailable();g.cn(this.ub(),a);g.Up(this.context.F.getRootNode(),g.RW.IV_DRAWER_ENABLED,a);x4(this.F)};
g.k.destroy=function(){this.F.Nz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.xC(this.Z);g.Rz(this.Oa);this.Wa&&this.Wa.dispose();this.D&&this.D.dispose();S4.prototype.destroy.call(this)};
g.k.u2=function(){if(this.B){d5(this.context.logger,a5(this).Ni.close);var a=g.OE();a&&this.J&&g.BP(a,this.J);W4(this)}};
g.k.N2=function(){g.Up(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.B4=function(){var a=g.OE(),b=a5(this);b=b?b.cg:this.cg;a&&b&&g.zP(a,[b])};
g.k.A4=function(){var a=g.OE(),b=a5(this);b=b?b.cg:this.cg;a&&b&&g.AP(a,[b])};
g.k.OZ=function(){var a=a5(this);d5(this.context.logger,a.Ni.gY);var b=g.OE();b&&a&&g.zP(b,[a.dl,a.cg])};
g.k.C4=function(){var a=g.OE(),b=a5(this);a&&b&&g.AP(a,[b.dl])};
g.k.NZ=function(a){var b=a5(this),c=g.OE();this.j?a?(a=this.context.logger,d5(a,b.Ni.jI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.dl&&g.BP(c,b.dl)):(a=this.context.logger,d5(a,b.Ni.jI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.cg&&g.BP(c,b.cg)):(a=this.context.logger,d5(a,b.Ni.jI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.cg&&g.BP(c,this.cg))};g.x(b5,S4);b5.prototype.QD=function(){S4.prototype.QD.call(this);Odb(this)};
b5.prototype.show=function(){S4.prototype.show.call(this);var a=g.OE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zP(a,[g.LE(b.itct)])};
b5.prototype.hide=function(){S4.prototype.hide.call(this);var a=g.OE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.AP(a,[g.LE(b.itct)])};g.x(c5,b5);
c5.prototype.show=function(){if(!this.isActive){b5.prototype.show.call(this);if(!this.J){g.Qp(this.ub(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.cn(this.u,!1);var b=this.createElement({G:"button",Ia:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.ub().appendChild(b);var c=this.annotation.df();c&&T4(this,b,
c,this.annotation.id,a.session_data);Sdb(this,a);this.J=!0}g.cn(this.ub(),!0);this.isActive=!0;this.u&&(Pdb(this,this.u),g.Qp(this.context.F.getRootNode(),"ytp-branding-shown"))}};
c5.prototype.hide=function(){this.isActive&&(b5.prototype.hide.call(this),g.cn(this.ub(),!1),this.isActive=!1,g.Sp(this.context.F.getRootNode(),"ytp-branding-shown"))};
c5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);b5.prototype.destroy.call(this)};g.x(Udb,b5);g.k=Udb.prototype;g.k.show=function(){this.isActive||(b5.prototype.show.call(this),this.ea||(Wdb(this),this.ea=!0),g.cn(this.ub(),!0),g.Mf(function(){g.Sp(this.ub(),"iv-promo-inactive")},100,this),this.ub().removeAttribute("aria-hidden"),this.isActive=!0,$db(this),Xdb(this),Ydb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.Qp(this.ub(),"iv-promo-inactive"),this.isActive=!1,this.ub().setAttribute("aria-hidden","true"))};
g.k.ZI=function(a,b,c,d,e,f){return this.isCollapsed?!1:b5.prototype.ZI.call(this,a,b,c,d,e,f)};
g.k.J3=function(a){this.T=!0;Vdb(this,500,a)};
g.k.I3=function(){this.T=!1;Zdb(this)};
g.k.D3=function(a){a.stopPropagation();this.hide()};
g.k.E3=function(a){a.stopPropagation();$db(this);this.isCollapsed=!0;g.Qp(this.ub(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();b5.prototype.destroy.call(this)};g.x(beb,g.sT);g.k=beb.prototype;g.k.rh=function(a,b){if(!peb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.b8a(b))&&geb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Ddb(this.j,b),x4(this.player)),!0}return null};
g.k.getOptions=function(){return peb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.jw=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.rd&&a.Z||g.hS(this.player.app)?!1:1===c&&!b.SR||a.La.get(b.videoId)||g.cN(b)||g.dN(b)?!0:!1};
g.k.aH=function(){if(this.B){var a=this.player.jb().getVideoContentRect(!0);g.an(this.B.element,a.width,a.height);g.Xm(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Ak();a=this.j;b=b.width;g.Up(a.C,"iv-drawer-small",426>=b);g.Up(a.C,"iv-drawer-big",1280<=b)}};
g.k.PZ=function(a){deb(this,a.state);g.hO(a.state,2)&&(this.pk()&&this.xo()&&2!==this.player.getPresentingPlayerType()&&this.Oz(!1),this.Nz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Gy(h)&&h.responseXML?h.responseXML:null)&&(geb(b,h),g.Qp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.sT.prototype.load.call(this);deb(this,this.player.Eb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.pA()&&(a=heb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().La.get(d);f&&ieb(e,f);f=f&&(f.EK||f.dB);if(!c.oA||f)c.Oa?eeb(this,c.Oa,e):(this.yw=function(){if(!b.J)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.bN(h))&&!b.ea){var l,m;if(h=null==(l=h.jd)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)b.ea=!0,neb(b,h),h.headerText&&b.gh&&(l=g.qE(h.headerText),b.gh.setAttribute("title",l))}},this.player.addEventListener("videodatachange",
this.yw));
g.uS(this.player,this.B.element,4);this.aH();(f=g.cN(c))&&neb(this,f);(f=g.dN(c))&&f.featuredChannel&&oeb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.gh=g.Te("ytp-cards-button",this.player.getRootNode())};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Oa&&eeb(this,b.Oa,a)};
g.k.unload=function(){this.player.lf("annotations_module");for(var a=g.w(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.T=null;this.j&&(this.j.destroy(),this.j=null,x4(this.player));this.J=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.I={};this.u.hide();g.sT.prototype.unload.call(this);this.B.detach();this.yw&&(this.player.removeEventListener("videodatachange",this.yw),this.yw=null)};
g.k.HW=function(a){a===this.player.getVideoData().videoId&&(this.loaded?jeb(this):this.load())};
g.k.pk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.xo=function(){return!!this.j&&this.j.B};
g.k.Oz=function(a,b,c){b=void 0===b?!1:b;this.pk();this.j&&(a?c?V4(this.j,c,b):V4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):W4(this.j))};
g.k.Nz=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.qa=function(){this.player.V().La.unsubscribe("vast_info_card_add",this.HW,this);g.Sp(this.player.getRootNode(),g.RW.IV_DRAWER_OPEN);for(var a=this.Z,b=g.Ap,c=0,d=a.length;c<d;c++)b.Hm(a[c]);this.Z.length=0;g.sT.prototype.qa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.rT("annotations_module",beb);g.rT("creatorendscreen",Wcb);})(_yt_player);
